# Generated by Django 5.0.6 on 2024-05-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pond_alter_feeding_options_duck_age_duck_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duck',
            name='ponds',
            field=models.ManyToManyField(related_name='ducks', to='main_app.pond'),
        ),
    ]
